"""Raw pipeline - Data Ingestion."""

from kedro.pipeline import Pipeline, node, pipeline

from .nodes import (
    validate_schema,
    reformat_columns,
    create_spine,
    create_prm_customers,
    create_prm_vehicles,
    create_prm_branches,
    create_prm_geolocation,
    create_prm_transactions,
    create_branches_features,
    create_churn_features,
    create_segment_features,
    create_geolocation_features,
    create_mileage_features,
    create_sales_features,
    create_special_trx_features,
    create_customer_vehicle_features,
    create_ftr_windows_transactions,
    ftr_join_dfs_spine
)


def create_pipeline(**kwargs) -> Pipeline:
    return pipeline(
        [
            node(
                func=validate_schema,
                inputs={
                    "parameters": "params:schemas",
                    "transactions": "raw_transactions",
                    "customers": "raw_customers",
                    "vehicles": "raw_vehicles",
                    "branches": "raw_branches",
                    "world_pop": "raw_world_pop",
                },
                outputs="memory.boolean",
                name="schema_validation",
                tags=["raw_layer", "ingestion"],
            ),
            node(
                func=reformat_columns,
                inputs={
                    "parameters": "params:schemas",
                    "scema_validation_boolean": "memory.boolean",
                    "transactions": "raw_transactions",
                    # "geospatial": "raw_geospatial",
                    "world_pop": "raw_world_pop",
                    "customers": "raw_customers",
                    "vehicles": "raw_vehicles",
                    "branches": "raw_branches",
                    # "competitors": "raw_competitors",
                },
                outputs={
                    "transactions": "int_transactions",
                    # "geospatial": "int_geospatial@spark",
                    "world_pop": "prm_world_pop@spark",
                    "customers": "int_customers@spark",
                    "vehicles": "int_vehicles@spark",
                    "branches": "int_branches@spark",
                    # "competitors": "int_competitors@spark",
                },
                name="columns_formatting",
                tags=["intermediate_layer", "ingestion"],
            ),
            node(
                func=create_spine,
                inputs={
                    "customers_info": "int_customers@spark",
                    "vehicles_info": "int_vehicles@spark",
                    "transactions_info": "int_transactions",
                    "start_dt": "params:spine_start_dt",
                    "end_dt": "params:spine_end_dt",
                    "frequency": "params:spine_frequency",
                    "customers_to_remove": "params:customers_to_remove",
                },
                outputs="prm_spine",
                name="create_spine",
                tags=["primary_layer", "ingestion", "spine"],
            ),
            node(
                func=create_prm_customers,
                inputs={
                    "customers_info": "int_customers@spark",
                },
                outputs="prm_customers",
                name="create_prm_customers",
                tags=["primary_layer", "ingestion"],
            ),
            node(
                func=create_prm_vehicles,
                inputs={
                    "vehicles_info": "int_vehicles@spark",
                },
                outputs="prm_vehicles",
                name="create_prm_vehicles",
                tags=["primary_layer", "ingestion"],
            ),
            node(
                func=create_prm_branches,
                inputs={
                    "branches_info": "int_branches@spark",
                },
                outputs="prm_branches@spark",
                name="create_prm_branches",
                tags=["primary_layer", "ingestion"],
            ),
            node(
                func=create_prm_geolocation,
                inputs={
                    "prm_branches": "prm_branches@pandas",
                    "geospatial_poi": "prm_geospatial_poi",
                    "geospatial_highways": "prm_geospatial_highways",
                    "geospatial_subways": "prm_geospatial_subways",
                    "world_pop": "prm_world_pop@pandas",
                },
                outputs="prm_geolocation@pandas",
                name="create_prm_geolocation",
                tags=["primary_layer", "geolocation"],
            ),
            node(
                func=create_prm_transactions,
                inputs={
                    "transactions_data": "int_transactions",
                    "spine": "prm_spine",
                    "prm_customers": "prm_customers",
                    "prm_vehicles": "prm_vehicles",
                    "prm_geolocation": "prm_geolocation@spark",
                    "branches_to_drop": "params:branches_to_drop",
                    "products_to_drop": "params:products_to_drop",
                },
                outputs="prm_transactions",
                name="create_prm_transactions",
                tags=["primary_layer", "ingestion"],
            ),
            node(
                func=create_sales_features,
                inputs={
                    "spine": "prm_spine",
                    "base_sales": "prm_transactions",
                },
                outputs="ftr_sales",
                name="create_sales_features",
                tags="feature_layer",
            ),
            node(
                func=create_mileage_features,
                inputs={
                    "spine": "prm_spine",
                    "ftr_sales": "prm_transactions",
                    "ftr_customer_vehicle": "ftr_vehicle",
                    "oem_rules": "raw_servicing_rules@pandas",
                },
                outputs="ftr_mileage",
                name="create_mileage_features",
                tags="feature_layer",
            ),
            node(
                func=create_geolocation_features,
                inputs={
                    "spine": "prm_spine",
                    "base_sales": "prm_transactions",
                    "prm_geolocation": "prm_geolocation@spark",
                },
                outputs="ftr_geolocation",
                name="create_geolocation_features",
                tags="feature_layer",
            ),
            node(
                func=create_customer_vehicle_features,
                inputs={
                    "spine": "prm_spine",
                    "base_sales": "prm_transactions",
                    "prm_customers": "prm_customers",
                    "prm_vehicles": "prm_vehicles",
                },
                outputs="ftr_vehicle",
                name="create_vehicle_features",
                tags="feature_layer",
            ),
            node(
                func=create_churn_features,
                inputs={
                    "spine": "prm_spine",
                    "ftr_sales": "ftr_sales",
                    "ftr_mileage": "ftr_mileage",
                },
                outputs="ftr_churn",
                name="create_churn_features",
                tags="feature_layer",
            ),
            node(
                func=create_special_trx_features,
                inputs={
                    "base_sales": "prm_transactions",
                    "prm_promo": "raw_promos",
                },
                outputs="ftr_special_trxs",
                name="create_special_trx_features",
                tags="feature_layer",
            ),
            node(
                func=create_segment_features,
                inputs={
                    "spine": "prm_spine",
                    "ftr_sales": "ftr_sales",
                    "ftr_mileage": "ftr_mileage",
                    "ftr_special_trxs": "ftr_special_trxs",
                },
                outputs="ftr_segment",
                name="create_segment_features",
                tags="feature_layer",
            ),
            node(
                func=create_branches_features,
                inputs={
                    "spine": "prm_spine",
                    "base_sales": "prm_transactions",
                    "prm_branches": "prm_branches@spark",
                    "ftr_mileage": "ftr_mileage",
                },
                outputs="ftr_branches",
                name="create_branches_features",
                tags="feature_layer",
            ),
            node(
                func=create_ftr_windows_transactions,
                inputs={
                    "input_data": "ftr_sales",
                    "instructions": "params:transactions.sales.instructions",
                    "sequential": "params:transactions.sequential",
                    "params_keep_cols": "params:transactions.keep_cols",
                },
                outputs="ftr_windows_sales",
                name="create_ftr_transactions",
                tags="feature_layer",
            ),
            node(
                func=ftr_join_dfs_spine,
                inputs={
                    "spine": "prm_spine",
                    # "prm_customer": "prm_customers",
                    # "prm_vehicles": "prm_vehicles",
                    # "prm_branches": "prm_branches@spark",
                    "ftr_vehicle": "ftr_vehicle",
                    "ftr_segment": "ftr_segment",
                    "ftr_branches": "ftr_branches",
                    "ftr_sales": "ftr_sales",
                    "ftr_mileage": "ftr_mileage",
                    "ftr_special_trxs": "ftr_special_trxs",
                    "ftr_geolocation": "ftr_geolocation",
                    "ftr_windows_sales": "ftr_windows_sales",
                    "ftr_churn": "ftr_churn",
                },
                outputs="ftr_master@spark",
                name="create_ftr_master",
                tags=["feature_layer", "master"],
            ),
        ],
        namespace="transactions",
    )
